server:
  port: 8083

spring:
  application:
    name: demo-app
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
security:
  token:
    secret: mySecret
    maxAgeSeconds: 86400 #1 day