server:
  port: 8083

spring:
  application:
    name: demo-app
  profiles:
    active: prod
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
security:
  token:
    secret: mySecret
    maxAgeSeconds: 86400 #1 day