server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  liquibase:
    contexts: dev
  devtools:
    remote:
      secret: secret
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

security:
  token:
    secret: Test
    maxAgeSeconds: 86400 #1 day