spring:
  application:
    name: film data base
  profiles:
    active: prod
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  logging:
    level:
      ROOT: DEBUG
      liquibase: DEBUG
      com.example.demo: DEBUG
      org.hibernate: DEBUG
      org.springframework.web: DEBUG
    pattern:
      console: %d{yyyy-MM-dd HH:mm:ss} - %msg%n
      file: %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
---
security:
  token:
    secret: ultra-super-secret
    maxAgeSeconds: 86400 #1 day
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  liquibase:
    contexts: dev
  devtools:
    remote:
      secret: secret
server:
  port: 8085