spring:
  application:
    name: uaa-service
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    pattern:
      console: %d{yyyy-MM-dd HH:mm:ss} - %msg%n
      file: %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
---
logging.level.org.hibernate.validator.internal: DEBUG
logging.level.org.hibernate.jpa.internal: DEBUG
logging.level.org.hibernate.integrator.internal: DEBUG
logging.level.org.hibernate.boot.registry.internal: DEBUG
logging.level.org.hibernate.id.factory.internal: DEBUG  #id generation info
logging.level.org.hibernate.internal: DEBUG  #Display properties of the session factory
logging.level.org.event.internal: DEBUG  #Display properties of the session factory
---
security:
  token:
    secret: mySecret
    maxAgeSeconds: 86400 #1 day
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    initialize: true
  h2:
    console:
      enabled: true
    tcp:
      enabled: rtue
  liquibase:
    contexts: dev
  devtools:
    remote:
      secret: secret